### 파트너 등록
POST http://localhost:8080/api/v1/partners
Content-Type: application/json

{
  "partnerName": "테스트",
  "businessNo": "1234123456",
  "email": "greg.shiny82@gmail.com"
}

### 파트너 조회
GET http://localhost:8080/api/v1/partners/ptn_kc9d66jIcMcrMe3l
Content-Type: application/json

{
}

### 파트너 활성화
POST http://localhost:8080/api/v1/partners/enable/ptn_eXWYFng43w7JTErD
Content-Type: application/json

{
}

### 파트너 비활성화
POST http://localhost:8080/api/v1/partners/disable/ptn_eXWYFng43w7JTErD
Content-Type: application/json

{
}
